"""Added users table

Revision ID: 6b014be4f207
Revises: caea580ee13f
Create Date: 2026-03-13 11:07:00.565807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b014be4f207'
down_revision: Union[str, Sequence[str], None] = 'caea580ee13f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dob')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
